version: "3.0"
services:
  app:
    mem_reservation: 2g
    mem_limit: 4g
    logging:
      driver: awslogs
      options:
        awslogs-group: corenlp
        awslogs-region: us-east-1
    image: 681762360827.dkr.ecr.us-east-1.amazonaws.com/graham3333/corenlp-complete
    ports: ["9000:9000"]
