version: "2"
services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    logging:
      driver: awslogs
      options:
        awslogs-group: corenlp
        awslogs-region: us-east-1
        awslogs-stream-prefix: corenlp
