version: "2"
services:
  app:
    mem_reservation: 4g
    mem_limit: 8g
    image: graham3333/corenlp-complete
    ports: ["9000:9000"]
    command: [
      'java', '-Xmx4g', '-cp', '*',
      'edu.stanford.nlp.pipeline.StanfordCoreNLPServer',
      '-port', '9000',
      '-timeout', '120000',
      '-threads', '8',
      '-maxCharLength', '-1',
      '-preload', 'tokenize,ssplit,pos,lemma,depparse,ner,coref',
    ]
