#!/usr/bin/env bash

# This is a thin wrapper around the `ecs-cli` command line tool to set sensible
# defaults for this project. It also makes the `ecs-cli up` comamnd more
# seamless by creating a `default` keypair and using the default vpc, security groups
# etc.

set -e

export ECS_CLUSTER=default
export COMPOSE_PROJECT_NAME=corenlp
export AWS_PROFILE=al2
export AWS_REGION=us-east-1

error() {
    >&2 echo "[ERROR] $@"
}

case $1 in

    up)

        KEY_PAIR_NAME=default
        PEM_FILE_PATH="$HOME/.ssh/${AWS_PROFILE}_${KEY_PAIR_NAME}.pem"

        # Get Default VPC
        VPC_ID=$(aws ec2 describe-vpcs --query 'Vpcs[?IsDefault==`true`].VpcId' --output text)

        SUBNET_IDS=$(aws ec2 describe-subnets \
            --query "Subnets[?VpcId==\`$VPC_ID\`].SubnetId" --output text  | tr -s '[:blank:]' ',')

        # Get Default Security Group
        SECURITY_GROUP=$(aws ec2 describe-security-groups \
            --group-names default \
            --query 'SecurityGroups[0].GroupId' --output text)

        # Get current IP and convert to CIDR block for adding to default security group
        CIDR=$(curl -s http://checkip.amazonaws.com)/32

        # Add CIDR block to default security group
        set +e
        SG_INGRESS_CHECK=$(aws ec2 authorize-security-group-ingress \
            --group-name default \
            --ip-permissions IpProtocol=-1,IpRanges="[{CidrIp=$CIDR}]" 2>&1)
        set -e

        # Do not print error if CIDR block already exists in security group
        case $SG_INGRESS_CHECK in
            *"InvalidPermission.Duplicate"*)
                # Do Nothing on InvalidPermission.Duplicate
                ;;
            *)
                echo "$SG_INGRESS_CHECK"
                ;;
        esac

        # Check if `default` key-pair exists and create new key-pair if not
        CHECK_KEY_PAIR=$(aws ec2 describe-key-pairs --query "KeyPairs[?KeyName==\`$KEY_PAIR_NAME\`].KeyName" --output text)
        if [ -z $CHECK_KEY_PAIR ]; then
            echo "$KEY_PAIR_NAME keypair does not exist. creating..."
            PEM=$(aws ec2 create-key-pair --key-name default --query 'KeyMaterial' --output text)
            touch "$PEM_FILE_PATH"
            echo "$PEM" > "$PEM_FILE_PATH"
            chmod 600 "$PEM_FILE_PATH"
            echo "created ${KEY_PAIR_NAME} key pair at ${PEM_FILE_PATH}"
        fi

        ecs-cli up \
            --launch-type EC2 \
            --instance-type "a1.xlarge" \
            --size 3 \
            --keypair "$KEY_PAIR_NAME" \
            --vpc "$VPC_ID" \
            --subnets "$SUBNET_IDS" \
            --security-group "$SECURITY_GROUP" \
            --capability-iam

        ;;

    scale)

        ecs-cli scale --capability-iam "$@"

        ;;

    *)
        ecs-cli "$@"
        ;;

esac